# Generated by Django 4.2.7 on 2023-11-10 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', message='Имя пользователя содержит недопустимый символ')], verbose_name='Имя пользователя'),
        ),
    ]
