# Generated by Django 4.2.7 on 2023-11-09 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredient_remove_ingridient_measurement_unit'),
        ('recipes', '0003_alter_ingredientsrecipes_ingredient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingridient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.measurementunit', verbose_name='Единица измерения'),
        ),
    ]
