# Generated by Django 4.2.7 on 2023-11-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_delete_ingridient_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementunit',
            name='measurement_unit',
            field=models.CharField(max_length=200, unique=True, verbose_name='Единица измерения'),
        ),
    ]
