version: '3.3'
services:

  app:
    build:
      dockerfile: /docker/django/Dockerfile
    volumes:
      - ./backend/:/code
      - media:/media
      - static:/static
    env_file:
      - /config/.env
    ports:
      - "8000:8000"
    command: bash run_dev.sh
    depends_on:
      - db

  frontend:
    build:
      dockerfile: /docker/frontend/Dockerfile
    volumes:
      - static:/static/
    command: cp -r build/. /static/

  nginx:
    build:
      dockerfile: /docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media

  db:
    image: postgres:13.10
    ports:
      - "5432:5432"
    env_file:
      - /config/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  static:
  media:
