# Generated by Django 4.2.7 on 2023-11-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_ingredientsrecipes_ingredient_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientsrecipes',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_ingredientsrecipes_for_user'),
        ),
    ]
