# Generated by Django 4.2.7 on 2023-11-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_ingredientsrecipes_unique_ingredientsrecipes_for_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientsrecipes',
            name='unique_ingredientsrecipes_for_user',
        ),
        migrations.AddConstraint(
            model_name='ingredientsrecipes',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_ingredients_for_recipe'),
        ),
        migrations.AddConstraint(
            model_name='recipestags',
            constraint=models.UniqueConstraint(fields=('recipe', 'tags'), name='unique_tags_for_recipe'),
        ),
    ]
